### PR TITLE
Adds the calling class to the string for the ajax hash to prevent collisions

### PR DESCRIPTION
**Pull request by mslinnea**
Addresses https://github.com/alleyinteractive/wordpress-fieldmanager/issues/621

### CODE REVIEW

**Review by dlh01 — APPROVED** [review]
🌳 I wondered whether the post, term, and user datasources should get the same fix, since they override the default `get_ajax_action()`. But I see that each has a distinct leading string like `fm_datasource_post` and `fm_datasource_term`...except for the user datasource, which also uses `fm_datasource_post` (oops!). Can we switch that to `fm_datasource_user` while we're here? (Or drop the `_type_` prefix from each and use `get_called_class()` like in the parent class.)

**Comment by mboynes** [comment]
> except for the user datasource, which also uses `fm_datasource_post`

😆

**Comment by mslinnea** [comment]
@dlh01 I updated the other classes to all use `get_called_class()` since that will prevent this same issue if those classes were extended.

**Comment by dlh01** [comment]
@mslinnea Unfortunately, it seems that using `get_called_class()` on its own will cause datasources to break when the class name is under a namespace: The action name in `$_POST` will get slashed and will no longer match the action name generated by Fieldmanager, like `\\My\\Datasource` instead of `\My\Datasource`.

I'm wondering whether the class name should be part of the hashed string instead, so maybe `fm_datasource_{$hash}`.

**Comment by mslinnea** [comment]
@dlh01 Valid point, I've updated these so that the called class is part of the hash, and I also fixed the preface for the user datasource.

**Review by dlh01 — APPROVED** [review]
🌳 Now we're cookin' with `get_called_class()`!

**Pull request merged**
