### PR TITLE
Bump the version UP

### LINKED ISSUE #411: 1.0.0 release
Last release 1.0.0 beta2 was released Jan 15: https://github.com/alleyinteractive/wordpress-fieldmanager/releases There have been many improvements since then.

A nice and clean cutpoint is useful for packaging, for example grabbing a zip off Github during an automated build process.  

Can a codeslinger get an official 1.0 release?

### PR DESCRIPTION
**Pull request by mboynes**
Official 1.0.0 release.

Resolves #411.

## TODO

* [x] Bump all static asset versions
* [x] Update api.fieldmanager.org

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Shouldn't we wait for any bugs to appear during RC for a week or two?

**Comment by mboynes** [comment]
Just getting it ready :-D.

**Comment by danielbachhuber** [comment]
;)

**Comment by mboynes** [comment]
http://api.fieldmanager.org/ has been updated. I'll update it again if anything changes.

**Pull request merged**
