### PR TITLE
Add filter for fm_calculated_context() to support additional contexts and overrides

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Includes hook docs! :)

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Let's get this into 1.0.0 before it's too late :)

**Comment by danielbachhuber** [comment]
> Let's get this into 1.0.0 before it's too late

What are you trying to use it for? Can you share more details on your use case?

**Comment by sc0ttkclark** [comment]
I was hoping to utilize this in additional contexts not yet supported, although it started out as me not fully understanding submenus covered settings pages. I thought this might be a useful hook in the future to help aide in integration with custom REST API endpoints (to tell FM what the context is, since it may not detect it).

**Comment by bcampeau** [comment]
There's already a branch for REST API integration that adds a custom context function. That will supersede this.

Submenus pages are already covered too. I think we should likely close this.

**Comment by sc0ttkclark** [comment]
Not including a filter like this would not promote integration testing in the future, just saying.

**Comment by mboynes** [comment]
I like the idea in general, but it's too easy to inadvertently break things using this filter. I'm going to sleep on it and look at the code tomorrow; I think there's another place we could do this that would be safer.

**Comment by sc0ttkclark** [comment]
What if we run it only if calculated context is empty?

**Comment by dlh01** [comment]
It looks to me like this was added in #510.

**Comment by mboynes** [comment]
Closing, as this was added in #510 as david noted.

**Pull request closed without merging**
