### PR TITLE
Add term presave value filter

### PR DESCRIPTION
**Pull request by firejdl**
Add filter to Fieldmanager_Datasource_Term::presave_alter_values(), which allows themes and other plugins to filter the term values before they are saved.

### CODE REVIEW

**Comment by dlh01** [comment]
Hey @firejdl, 

What's your use case for this filter?

**Comment by firejdl** [comment]
We need primary tags to be specified in a separate field from regular tags, but we also want primary tags to be added as regular tags. This change allows for that.

**Comment by dlh01** [comment]
Where is the primary tag stored?

**Comment by firejdl** [comment]
It's stored as postmeta as well as one of the regular tags.

**Comment by dlh01** [comment]
It sounds like you might be able to extend `Fieldmanager_Datasource_Term` to accomplish what you need. You could use a custom `save_taxonomy()` method that appended the primary tag after the rest of the tags are set. Something like:

```php

class My_Datasource extends Fieldmanager_Datasource_Term {

	public function save_taxonomy( $tax_values, $data_id ) {
		parent::save_taxonomy( $tax_values, $data_id );
		if ( $primary_tag = get_post_meta( $data_id, 'my_meta_key', true ) ) {
			wp_set_object_terms( $data_id, (int) $primary_tag, 'post_tag', true );
		}
	}

}
```

Would that work?

**Comment by firejdl** [comment]
For one thing, we want to delete the old primary tag from the list of regular tags when you change primary tags. That's only possible with knowing the previous/current value, as in `presave_alter_values` (and the filter).

I realize that I could also extend `Fieldmanager_Datasource_Term`, modify the `$values` in `presave_alter_values()`, and then call `parent::presave_alter_values()`, but using a filter feels more like the WordPress way to do it...

**Comment by firejdl** [comment]
We switched over to the extending `Fieldmanager_Datasource_Term` method a while back and I forgot to close this PR. :)

**Pull request closed without merging**
