### PR TITLE
Updating documentation to reflect the possibility of multiple display_if values...

### PR DESCRIPTION
**Pull request by kkoppenhaver**
...Clarifies alleyinteractive/wordpress-fieldmanager#618

### CODE REVIEW

**Comment by kkoppenhaver** [comment]
PHP 7 test looks to have failed because of config issues...

```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /tmp/wordpress-tests-lib/includes/testcase.php on line 15
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/7.0.17/bin/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /home/travis/.phpenv/versions/7.0.17/bin/phpunit:468
PHP   3. PHPUnit\TextUI\Command->run() phar:///home/travis/.phpenv/versions/7.0.17/bin/phpunit/phpunit/TextUI/Command.php:136
PHP   4. PHPUnit\TextUI\Command->handleArguments() phar:///home/travis/.phpenv/versions/7.0.17/bin/phpunit/phpunit/TextUI/Command.php:147
PHP   5. PHPUnit\TextUI\Command->handleBootstrap() phar:///home/travis/.phpenv/versions/7.0.17/bin/phpunit/phpunit/TextUI/Command.php:731
PHP   6. PHPUnit\Util\Fileloader::checkAndLoad() phar:///home/travis/.phpenv/versions/7.0.17/bin/phpunit/phpunit/TextUI/Command.php:910
PHP   7. PHPUnit\Util\Fileloader::load() phar:///home/travis/.phpenv/versions/7.0.17/bin/phpunit/phpunit/Util/Fileloader.php:39
PHP   8. include_once() phar:///home/travis/.phpenv/versions/7.0.17/bin/phpunit/phpunit/Util/Fileloader.php:55
PHP   9. require() /home/travis/build/alleyinteractive/wordpress-fieldmanager/tests/php/bootstrap.php:26
PHP  10. require() /tmp/wordpress-tests-lib/includes/bootstrap.php:97
```


PHP 5.6 fails because of PHPCS warnings:

```FILE: ...ress-fieldmanager/php/util/class-fieldmanager-util-term-meta.php
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 230 | ERROR | Assignments must be the first block of code on a line
     |       | (Squiz.PHP.DisallowMultipleAssignments.Found)
 308 | ERROR | Assignments must be the first block of code on a line
     |       | (Squiz.PHP.DisallowMultipleAssignments.Found)
 308 | ERROR | get_page_by_path() is prohibited, please use
     |       | wpcom_vip_get_page_by_path() instead.
     |       | (WordPress.VIP.RestrictedFunctions.get_page_by_path_get_page_by_path)
 324 | ERROR | Assignments must be the first block of code on a line
     |       | (Squiz.PHP.DisallowMultipleAssignments.Found)
----------------------------------------------------------------------
```

**Comment by dlh01** [comment]
@kkoppenhaver Your added documentation make sense to me. I opened #620 to address the Travis issues.

**Comment by kkoppenhaver** [comment]
@dlh01 Great! Following #620.

**Comment by kkoppenhaver** [comment]
@dlh01 Do we need to re-run travis/is this something I can trigger?

**Comment by dlh01** [comment]
I think merging `master` into your branch will cause Travis to run again.

**Comment by kkoppenhaver** [comment]
@dlh01 Travis fixes look good. Thanks for your help with those.

**Comment by kkoppenhaver** [comment]
@dlh01 Anything else you need from me on this?

**Comment by dlh01** [comment]
I don't think so, thanks. This just needs a 👍 from a FM developer.

**Comment by mboynes** [comment]
Thanks @kkoppenhaver!

**Pull request merged**
