### PR TITLE
Reinit $messages as an array if validation_rules is not a string

### PR DESCRIPTION
**Pull request by terrarum**
I have a field with these validation rules:

```
'validation_rules'   => ['required' => true, 'min' => 1]
```

and I wanted to customise the error message for the `min` rule not being met, which I tried with

```
'validation_messages' => [
  'min' => 'You must select an image'
]
```

which did not work, and gave me this warning:

```
Warning: Illegal string offset 'min' in /vagrant/wordpress/plugins/fieldmanager/php/util/class-fieldmanager-util-validation.php on line 172
```

Investigating `class-fieldmanager-util-validation.php` showed that `$messages` is initialised as a string, but if `$fm->validation_rules` is not a string the code tries to treat `$messages` as an associative array.

### CODE REVIEW

**Comment by dlh01** [comment]
I'm not seeing any place in that method in which `$messages` is used as a string. If it's not, then perhaps `$messages` could just be initialized as an array to begin with.

**Comment by terrarum** [comment]
You are correct! Changed the original $messages to an array, removed my line, it worked.

**Comment by terrarum** [comment]
Hi @dlh01, not sure what the protocol is for this but is there any chance this could be reviewed and merged soon?

**Comment by dlh01** [comment]
@terrarum I'm not sure. It's a tiny change, but I think it might benefit from a second look by someone who's more familiar with the validation functionality than I am.

**Comment by terrarum** [comment]
@dlh01 fair enough, thank you!

**Comment by terrarum** [comment]
@kjbenk @bcampeau Hello, according to git you wrote most of class-fieldmanager-util-validation.php with some small tweaks from @mboynes, is there any chance one of you would be able to review my PR? Thank you!

**Comment by simonrcodrington** [comment]
When will this issue be addressed? 

I've ran into this exact same issue and after a while debugging why jQuery Validator functionality was not working. I ended up changing the `$messages` variables to an array and everything works as expected.

The documentation says that both a string or associative array can be used, but most people I feel will opt into using an array as you can easily specify multiple rules and messages e.g 

`        $textarea = new \Fieldmanager_TextArea(
            'Article Abstract',
            [
                'name'                => 'my_textarea',
                'attributes'          => [
                    'rows'        => 5,
                    'maxlength'   => 225
                ],
                'validation_rules'    => ['digits' => true, 'required' => true],
                'validation_messages' => ['digits'   => 'Only digits are allowed in here',
                                          'required' => 'This field is required, please complete it'
                ]
            ]
        );`

Without this bugfix the validation wont work.

**Comment by digiguru** [comment]
Given a number of people have approved this change (but none with write permission), may I politely ask someone with write permission (@dlh01) to consider a merge now?

Or is there something else you need for extra confidence?

**Pull request merged**
