### PR TITLE
Potential fix for fm_renumber and radios bug

### LINKED ISSUE #548: Radio values disappear upon dragging repeating sortable field group
I have a repeating sortable field group containing a set of radio fields. When I drag this group to re-order, the field values sometimes disappear. But when I save the post, the correct values reappear.

### PR DESCRIPTION
**Pull request by mboynes**
A proposed solution to the bug reported in #548, this code modifies `fm_renumber()` by adding a temporary and unique prefix to all modified field names during the renumbering process, then removes that prefix after renumbering is done.

I'm not sold on this approach, it feels like a lot of overhead.

Closes #548

### CODE REVIEW

**Comment by dlh01** [comment]
The `_.uniqueId()` function in Underscore is intended for "temporary DOM ids," which seems similar to what you're going for? http://underscorejs.org/docs/underscore.html#section-164

While that doesn't really reduce the "overhead" of the change (and might even increase the overhead because we need to make sure Underscore loads before `fieldmanager.js`, although #625 might have the same effect), it might allow us to offload some of the work to an existing library, and it might at least "feel" cleaner.

**Comment by mgburns** [comment]
Confirming that this branch does fix the issue for us! 🥇

**Comment by montchr** [comment]
It works for us too! Thank you.

**Comment by kaitlinbolling** [comment]
This fix worked for me! Can we get this merged?

**Comment by dlh01** [comment]
While it might be more overhead than ideal in theory (or might not), in practice there are many testimonials to it working, and no new approaches have been presented, so I think we can move ahead. We can always improve its performance in future PRs.

**Review by dlh01 — APPROVED** [review]
🌳

**Pull request merged**
