### PR TITLE
Turn active tab persistent to a Group option, defaulting to true

### PR DESCRIPTION
**Pull request by danielbachhuber**
Previously #189

### CODE REVIEW

**Comment by mboynes** [comment]
This is great, thanks! Can you bump the enqueue version on `js/fieldmanager-group-tabs.js` and then I'll merge it?

**Comment by danielbachhuber** [comment]
> bump the enqueue version

Yep, e8f6e90

**Comment by mboynes** [comment]
Thanks!

**Comment by danielbachhuber** [comment]
@mboynes any word on getting this to VIP?

**Pull request merged**
