### PR TITLE
Updating semver for composer/installers.

### PR DESCRIPTION
**Pull request by crazyjaco**
This is for issue #825.

### CODE REVIEW

**Comment by dlh01** [comment]
Thanks for the PR, @crazyjaco!

Is there any reason to _not_ bump `composer/installers` to `^2.0`, as you first proposed in the issue?

**Comment by crazyjaco** [comment]
The original constraint was ~1.0, which means 1.0, 1.0.1, 1.0.4 would be acceptable, but 1.2 or 1.4 would not.
Going to ^2.0 means that 2.0.2 and 2.5 would both be acceptable.

My concern going to 2.0 would force users to update other dependencies as well, but I guess thats not really this package's problem.

Honestly, it feels like the best solution is to remove the constraint entirely.
Thats what we did for most of our internal plugins.
The plugin/package works fine with most versions, if not all, so putting a constraint on it makes it difficult to maintain when a lot of plugins/packages are in play for a project.

**Comment by crazyjaco** [comment]
It looks like ">=1.0" would also work. I didn't realize that was an option until I just looked again.

I use this tool to figure out semver impact
https://semver.npmjs.com/

**Comment by dlh01** [comment]
Hey @crazyjaco — as you can see in the automated test results, the `>=` constraint fails Composer's `--strict` validation requirements. We might have to go with something like `^1.0 || ^2.0`.

**Comment by crazyjaco** [comment]
Thanks! Updated with that suggestion. I didn't realize you could list a constraint like that. Neat!

**Review by dlh01 — APPROVED** [review]

**Pull request merged**
