### PR TITLE
Datepicker should provide a minute default

### PR DESCRIPTION
**Pull request by montchr**
#296 

If minute field is empty and hour field contains a valid value, then set minutes value to `0`.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Seems fine to me. @mboynes  ?

**Comment by montchr** [comment]
Should I add a test for this?

**Comment by danielbachhuber** [comment]
> Should I add a test for this?

Sure!

**Comment by mboynes** [comment]
Thanks for the PR! A test would be great, then we can get this merged.

**Comment by montchr** [comment]
> Thanks for the PR! A test would be great, then we can get this merged.

You are welcome. I've been trying to track down this issue for weeks, and this seems to be the fix.

I'll have to set up a unit testing environment. Never done so before, but it's been on my list of things to do anyway. I'll update this PR later today and ping you guys.

**Comment by montchr** [comment]
@mboynes @danielbachhuber Added test, and an additional comment fix. Worked locally in PHPUnit, waiting on Travis.

**Comment by mboynes** [comment]
Thanks @montchr!

**Pull request merged**
